FROM --platform=linux/amd64 ubuntu:24.04

VOLUME /data

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-redis \
    python3-requests \
    python3-prometheus-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./job_monitor.py /app

EXPOSE 8080

CMD ["/usr/bin/python3", "job_monitor.py"]
