---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.redis.hostname }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: 6379
  selector:
    app: {{ .Values.redis.hostname }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.hostname }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.hostname }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.hostname }}
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        resources:
          requests:
            cpu: "{{ .Values.redis.resources.requests.cpu }}"
            memory: "{{ .Values.redis.resources.requests.memory }}"